# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{
  pkgs,
  fetchurl,
  fetchgit,
  fetchhg,
}:

self: super: {
  "cppy" = super.buildPythonPackage rec {
    pname = "cppy";
    version = "1.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/78/0c/deb4c3e24515d240428260457d2e2e23341fccc3125bdc170190eeba7824/cppy-1.3.0-py3-none-any.whl";
      sha256 = "1lqyrcvz1n862wyc3cwx8p3q7nd0h47yz8dlv027mnkg0zicljyx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [
      self."setuptools"
    ];
  };
  "cycler" = super.buildPythonPackage rec {
    pname = "cycler";
    version = "0.12.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e7/05/c19819d5e3d95294a6f5947fb9b9629efb316b96de511b418c53d245aae6/cycler-0.12.1-py3-none-any.whl";
      sha256 = "0c0d9s2mmb6b7jnbhnclb5017rbjb530i62jc50n9n12yb7zgkl5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "fonttools" = super.buildPythonPackage rec {
    pname = "fonttools";
    version = "4.60.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4b/42/97a13e47a1e51a5a7142475bbcf5107fe3a68fc34aef331c897d5fb98ad0/fonttools-4.60.1.tar.gz";
      sha256 = "1ndqhwp82mvrhv3iswy5zbrpy58947wwh92zn83fizpb742ay07g";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "kiwisolver" = super.buildPythonPackage rec {
    pname = "kiwisolver";
    version = "1.4.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/85/4d/2255e1c76304cbd60b48cee302b66d1dde4468dc5b1160e4b7cb43778f2a/kiwisolver-1.4.7.tar.gz";
      sha256 = "0q0ak10hwlyza21qhjkfq97xpaixb337q0fkhnvgf1vipn0zz4wq";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ self."cppy" ];
  };
  "matplotlib" = super.buildPythonPackage rec {
    pname = "matplotlib";
    version = "3.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8a/46/425a44ab9a71afd2f2c8a78b039c1af8ec21e370047f0ad6e43ca819788e/matplotlib-3.5.1.tar.gz";
      sha256 = "076f8qi265x8jy89c03r3vv5h4is4ir5mawwrrrpp96314783sdj";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [
      self."cycler"
      self."fonttools"
      self."kiwisolver"
      self."numpy"
      self."packaging"
      self."pillow"
      self."pyparsing"
      self."python-dateutil"
    ];
  };
  "meson" = super.buildPythonPackage rec {
    pname = "meson";
    version = "1.9.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9c/07/b48592d325cb86682829f05216e4efb2dc881762b8f1bafb48b57442307a/meson-1.9.1-py3-none-any.whl";
      sha256 = "1l4q8mb441nqhdjsazpzvb98x4bir4af2s9gacpj06h41ivsn97q";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "meson-python" = super.buildPythonPackage rec {
    pname = "meson-python";
    version = "0.18.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/28/58/66db620a8a7ccb32633de9f403fe49f1b63c68ca94e5c340ec5cceeb9821/meson_python-0.18.0-py3-none-any.whl";
      sha256 = "1qk892022w55189zlvjmxl6xd74lq13k51xvzvskihhwam8y03rv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [
      self."meson"
      self."packaging"
      self."pyproject-metadata"
      self."tomli"
    ];
  };
  "numpy" = super.buildPythonPackage rec {
    pname = "numpy";
    version = "2.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a9/75/10dd1f8116a8b796cb2c737b674e02d02e80454bda953fa7e65d8c12b016/numpy-2.0.2.tar.gz";
      sha256 = "0y3fcd268cnrc8ipcmj1c082an4j4a4wj3dbcjlf500qxryrhg48";
    };
    # format = "setuptools";
    pyproject = true;

    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ self."meson-python" ];
  };
  "packaging" = super.buildPythonPackage rec {
    pname = "packaging";
    version = "25.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/20/12/38679034af332785aac8774540895e234f4d07f7545804097de4b666afd8/packaging-25.0-py3-none-any.whl";
      sha256 = "1154669ydc149dash6yaf3n2byqiqvajf8isdc282xgin7r2wmr9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "pandas" = super.buildPythonPackage rec {
    pname = "pandas";
    version = "1.4.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c4/eb/cfa96ba42695b3c28d4864a796d492f188471dd536df7e5e5e0c54b629a6/pandas-1.4.1.tar.gz";
      sha256 = "1ll05fmga749dpxyfgr57wak6df4wgsi0322q655zjy7ib4kxfcd";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [
      self."numpy"
      self."python-dateutil"
      self."pytz"
    ];
  };
  "pillow" = super.buildPythonPackage rec {
    pname = "pillow";
    version = "11.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f3/0d/d0d6dea55cd152ce3d6767bb38a8fc10e33796ba4ba210cbab9354b6d238/pillow-11.3.0.tar.gz";
      sha256 = "08zmx0sy0xh6km2ll5l7psdn9l107vamm7i0ns8j02ydhrsywa1q";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [ pkgs.zlib-ng ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
    # configureFlags = [
    #   "--enable-zlib"
    # ];
  };
  "pyparsing" = super.buildPythonPackage rec {
    pname = "pyparsing";
    version = "3.2.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/10/5e/1aa9a93198c6b64513c9d7752de7422c06402de6600a8767da1524f9570b/pyparsing-3.2.5-py3-none-any.whl";
      sha256 = "0plslmwk06s0zirly759v3rx2nj9282qscixb7k1zx2c0q14z2p3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "pyproject-metadata" = super.buildPythonPackage rec {
    pname = "pyproject-metadata";
    version = "0.9.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7e/b1/8e63033b259e0a4e40dd1ec4a9fee17718016845048b43a36ec67d62e6fe/pyproject_metadata-0.9.1-py3-none-any.whl";
      sha256 = "1bbk35rwq17rc97s6659bxcfj9gxbafk3z2lldsrpvf393jzsppf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [
      self."packaging"
    ];
  };
  "python-dateutil" = super.buildPythonPackage rec {
    pname = "python-dateutil";
    version = "2.9.0.post0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ec/57/56b9bcc3c9c6a792fcbaf139543cee77261f3651ca9da0c93f5c1221264b/python_dateutil-2.9.0.post0-py2.py3-none-any.whl";
      sha256 = "09q48zvsbagfa3w87zkd2c5xl54wmb9rf2hlr20j4a5fzxxvrcm8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "pytz" = super.buildPythonPackage rec {
    pname = "pytz";
    version = "2025.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/81/c4/34e93fe5f5429d7570ec1fa436f1986fb1f00c3e0f43a589fe2bbcd22c3f/pytz-2025.2-py2.py3-none-any.whl";
      sha256 = "001gxkq46b96nzhdwymxzgvcng4g90snyjwgxck4ri6qdllpdpsx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "seaborn" = super.buildPythonPackage rec {
    pname = "seaborn";
    version = "0.13.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/83/11/00d3c3dfc25ad54e731d91449895a79e4bf2384dc3ac01809010ba88f6d5/seaborn-0.13.2-py3-none-any.whl";
      sha256 = "11qr6rjx5ympgbzmvfzjn5haab66sciz493rw9jj22fgz8v86vv3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [
      self."matplotlib"
      self."numpy"
      self."pandas"
    ];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.17.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b7/ce/149a00dd41f10bc29e5921b496af8b574d8413afcd5e30dfa0ed46c2cc5e/six-1.17.0-py2.py3-none-any.whl";
      sha256 = "0x1jdic712dylbnyiqdj4xyxrlx0gaacynmbmkfiym4hxn8z68a7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "tomli" = super.buildPythonPackage rec {
    pname = "tomli";
    version = "2.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/77/b8/0135fadc89e73be292b473cb820b4f5a08197779206b33191e801feeae40/tomli-2.3.0-py3-none-any.whl";
      sha256 = "06qzzfwkcir3n1rcl2vdgqhz3nbwqyzapd8975j9wzdhqprilnz9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
}
